apiVersion: api/v1
kind: Task
name: case-111
inputs:
- {name: dsn, type: String, default: mysql://host/db}
- {name: sysbench, type: Resource}
- {name: curl options, type: String, default: '--location', description: 'Additional options given to the curl bprogram. See https://curl.haxx.se/docs/manpage.html'}
outputs:
- {name: logs, type: Artifact, valueFrom: /root/logs/}
implementation:
  container:
    image: byrnedo/alpine-curl@sha256:548379d0a4a0c08b9e55d9d87a592b7d35d9ab3037f4936f5ccd09d0b625a342
    command:
    - sh
    - -exc
    - |
      url="$0"
      output_path="$1"
      curl_options="$2"
      mkdir -p "$(dirname "$output_path")"
      curl --get "$url" --output "$output_path" $curl_options
    - '{{inputs.dsn}}'
    env:
      "sysbench": "kkkk"
