apiVersion: 'api/v1'
kind: TaskRun
name: pipeline-222-run
spec:
  parent: plan-run-xxx
  acester: root-run-xxx
  # taskRef or TaskSpec
  taskRef:
    name: case-111
  taskSpec:
    # inputs no need, will be infered from invokation
    outputs:
    - {name: logs, type: Artifact, fromExpression: '{{steps.ts1.outputs.logs}}'}
    implementation:
      steps:
        # scheme from taskrun spec
        - name: ts1
          taskRef:
            name: case-111
          inputs:
          - {name: dsn, value: '{{inputs.dsn}}'}
          - {name: sysbench, value: "{{inputs.sysbench}}"}
          timeout: '2h'
        - name: ts2
          taskSpec:
            inputs:
            - {name: dsn, type: String, default: "mysql://host/db"}
            - {name: sysbench, type: Resource}
            outputs:
            - {name: logs, type: Artifact, valueFrom: /root/logs/}
            metadata:
            implementation:
              container:
                image: byrnedo/alpine-curl@sha256:548379d0a4a0c08b9e55d9d87a592b7d35d9ab3037f4936f5ccd09d0b625a342
                command:
                - sh
                - -exc
                - |
                  url="$0"
                  output_path="$1"
                  curl_options="$2"
                  mkdir -p "$(dirname "$output_path")"
                  curl --get "$url" --output "$output_path" $curl_options
                - '{{inputs.dsn}}'
          inputs:
          - {name: upperCase, value: '{{steps.ts1.outputs.exitCode}}'}
          timeout: '1h'
  inputs:
  - {name: dsn, value: mysql://host/db}
  - {name: sysbench, type: Resource, value: "xxxxx"}
  timeout: '2h'
status:
  completionTime: "2021-09-22T06:24:15Z"
  startTime: "2021-09-22T06:19:20Z"
  phase: complete/running/pending
  complete: success/fail/error
  taskSpec: # from above  # todo whether render after inputs
  inputs:
  - {name: dsn, value: mysql://host/db}
  - {name: sysbench, value: "xxxxx"}
  outputs:
  - {name: logs, type: Artifact, s3: 's3://remotepath'}
  children:
  - case-111-run