apiVersion: 'api/v1'
kind: TestbedSetup
metadata:
  id: 1
  createTime: "2021-09-22T06:19:20Z"
  createdBy: someone@pingcap.com
  updateTime: "2021-09-22T06:19:20Z"
  updateBy: someone@pingcap.com
spec:
  parent: 
    planRunID: 222
  testbedRef:
    planID: 5678
  testbedSpec:
    generateName: release-arm64-perftest-sysbench-hybrid-001
    resourcePool: arm64
    rmsUrl: ""
    items:
        - name: tiup
          type: WORKLOAD_NODE
          spec:
            container:
              image: hub.pingcap.net/qa/base-image
              imagePullPolicy: Always
              name: node
    reclaimPolicy:
        lease: 24h
        gcStrategy:
            onFailure:
                artifact:
                    monitor: true
                    log: true
  timeout: '2h'
  priority: 100
  outputs:
  - name: param1
    valueExpr: '{{testbed.items.tc.tidb.dsn}}'
status:
  schedule:
    scheduleStatus: pending/approved/refused/done
    scheduleMessage: "insufficient resource: requested {cpu:234}, resource pool 'benchbot' left {cpu: 123}"
    scheduleTime: "2022-02-15T08:66:23Z"
    nextScheduleTime: "2022-02-16T09:00:00Z"
    testbedSpec: null
  report:
    retryCnt: 3
    status: "polling/submmitting/done"
  run:
    startTime: "2021-09-22T06:19:20Z"
    completeTime: "2021-09-22T06:24:15Z"
    phase: pending/impending/running/success/failure/error/skipped/omitted
    outputs:
    - name: testbed
      value: "the handle"
    - name: param1
      value: "the dsn"
    underlying:
      argo:
        namespace: "testground"
        workflow: "flow3"
        templateName: "plan-2344-223"
        node: ""
        nodeUrl: ""
