apiVersion: 'api/v2'
kind: TestbedSetupRequest
metadata:
  id: 2347
spec:
  testbedSetupRunRef:
    id: 1234
  testbed:
    name: release-arm64-perftest-sysbench-hybrid-001-tps-1234
    generateName: release-arm64-perftest-sysbench-hybrid-001
    resourcePool: arm64
    rmsUrl: "http://rms.test-infra"
    physicalResourceRequest:
        cpu: {core: 3.5}
        memory: {byte: 100000}
    items:
        - name: tiup
          type: WORKLOAD_NODE
          spec:
            artifact:
              artifactPaths:
                  - /tiup/data/prometheus-9090
                  - /home/root/.tiup/logs
            container:
              image: hub.pingcap.net/qa/base-image
              imagePullPolicy: Always
              name: node
              nodeSelector:
                  kubernetes.io/hostname: 172.16.6.61
              resources:
                  requests: {cpu: '20', memory: 16Gi, storage: 1500Gi}
              securityContext:
                  capabilities: {add: [SYS_ADMIN, SYS_PTRACE, NET_ADMIN]}
              storageClassName: fast-disks
              volumeMount:
                  mountPath: /tiup
    reclaimPolicy:
        lease: 240h
        gcStrategy:
            onFailure:
                artifact:
                    monitor: true
                    log: true
                reserveEnv:
                    durationOnWorkingHour: 0h
                    scaleIn: false
                    scaleDown: false
status:
  scheduleStatus: UnSchedule/Wait/Scheduled/Refused
  lastUnscheduledReason: "insufficient resource: requested {cpu:234}, resource pool left {cpu: 123}"
